name: sq_compare
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - upsetplot
  - reportlab
   # R and edgeR
  - r-base=4.3
  - bioconductor-edger
  - xz
  - backports.lzma
  - rpy2
  
